name: Rust

on:
  workflow_dispatch:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Verify examples
      env:
        EXAMPLES: "basic-ownership","struct-ownership"
      run: for ex in $EXAMPLES; do cargo run --verbose --example $ex; done
